header:
  schema-version: 2.0.0
  last-updated: '2025-01-01'
  last-reviewed: '2025-01-01'
  url: https://github.com/meshery-extensions/meshery-consul/blob/master/.github/security-insights.yml
  comment: |
    This file contains the security insights information for the Meshery project.

project:
  name: meshery
  administrators:
    - name: Lee Calcote
      affiliation: Meshery
      email: leecalcote@gmail.com
      primary: true
  repositories:
    - name: meshery-consul
      url: https://github.com/meshery-extensions/meshery-consul
      comment: |
         Meshery adapter for Consul 
  vulnerability-reporting:
    reports-accepted: true
    bug-bounty-available: false

repository:
  url: https://github.com/meshery-extensions/meshery-consul
  status: active
  accepts-change-request: true
  accepts-automated-change-request: false
  core-team:
    - name: Lee Calcote
      affiliation: Meshery
      email: leecalcote@gmail.com
      primary: true
  license:
    url: https://github.com/meshery-extensions/meshery-consul/blob/master/LICENSE
    expression: https://github.com/meshery-extensions/meshery-consul/blob/master/LICENSE
  security:
    assessments:
      self:
        comment: |
          Self assessment has not yet been completed.
