name: user
vars:
  controlplaneNS: consul
  namespace: default
  consulVersion: 1.12.2
  profile: default
services:
  consulservicemesh:
    type: ConsulMesh
    namespace:  $(#ref.vars.controlplaneNS)
    settings:
      version: $(#ref.vars.consulVersion)
      profile: $(#ref.vars.profile)
    